baseurl: https://rand-notes.github.io
title: idk
languageCode: en-us
theme: thm
paginate: 10
disableSitemap: true
params:
  math: true
  dateform: 'Jan 2, 2006'
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02'
  disableReadOtherPosts: false
  enableSharingButtons: false
  defaultTheme: "dark"
  keywords: 'homepage, blog'
  images:
    - ''
taxonomies:
  category: blog
  tag: tags
  series: series
languages:
  en:
    title: idk
    keywords: ''
menu:
  main:
    - identifier: blog
      name: notes
      url: /posts
